"""Utility functions for summarizing quantitative research data."""
from __future__ import annotations

from typing import Dict, List, Tuple, Optional

NUMERIC_PRIORITY_KEYWORDS: Tuple[str, ...] = (
    "age",
    "income",
    "household",
    "spend",
    "cost",
    "budget",
    "price",
    "expenditure",
)

CATEGORICAL_PRIORITY_KEYWORDS: Tuple[str, ...] = (
    "gender",
    "sex",
    "occupation",
    "employment",
    "education",
    "region",
    "location",
    "city",
    "area",
    "income",
    "household",
    "marital",
)


def _score_column(name: str, keywords: Tuple[str, ...]) -> int:
    """Return a priority score for a column name based on keyword matches."""

    lowered = name.lower()
    for priority, keyword in enumerate(keywords[::-1], start=1):
        if keyword in lowered:
            return len(keywords) + priority

    # Penalise autogenerated survey question labels (e.g. Q1_, q12)
    if lowered.startswith("q") and any(char.isdigit() for char in lowered[:4]):
        return 0

    # Provide a minimal score so that we still return something if no keywords match
    return 1


def _take_top_items(
    items: List[Tuple[str, any, int]],
    limit: int,
) -> List[Tuple[str, any]]:
    """Return the top items sorted by score and name."""

    sorted_items = sorted(items, key=lambda item: (-item[2], item[0].lower()))
    return [(name, value) for name, value, _ in sorted_items[:limit]]


def select_priority_numeric_columns(
    numeric_summary: Optional[Dict[str, Dict[str, float]]],
    limit: int = 3,
) -> Dict[str, Dict[str, float]]:
    """Return a filtered subset of numeric columns prioritising demographic metrics."""

    if not numeric_summary:
        return {}

    scored: List[Tuple[str, Dict[str, float], int]] = []
    for name, stats in numeric_summary.items():
        if not isinstance(stats, dict):
            continue
        score = _score_column(name, NUMERIC_PRIORITY_KEYWORDS)
        if score > 0:
            scored.append((name, stats, score))

    if not scored:
        return {}

    selected = _take_top_items(scored, limit)
    return {name: numeric_summary[name] for name, _ in selected}


def select_priority_categorical_columns(
    categorical_summary: Optional[Dict[str, List[Dict[str, float]]]],
    limit: int = 3,
) -> Dict[str, List[Dict[str, float]]]:
    """Return a filtered subset of categorical columns prioritising demographic metrics."""

    if not categorical_summary:
        return {}

    scored: List[Tuple[str, List[Dict[str, float]], int]] = []
    for name, values in categorical_summary.items():
        if not isinstance(values, list) or not values:
            continue
        score = _score_column(name, CATEGORICAL_PRIORITY_KEYWORDS)
        if score > 0:
            scored.append((name, values, score))

    if not scored:
        return {}

    selected = _take_top_items(scored, limit)
    return {name: categorical_summary[name] for name, _ in selected}


def _format_numeric_stat(name: str, stats: Dict[str, float]) -> str:
    mean = stats.get("mean")
    median = stats.get("median")
    min_value = stats.get("min")
    max_value = stats.get("max")

    parts: List[str] = []
    if mean is not None:
        parts.append(f"mean {mean:.1f}")
    if median is not None:
        parts.append(f"median {median:.1f}")
    if min_value is not None and max_value is not None:
        parts.append(f"range {min_value:.1f}–{max_value:.1f}")

    stats_text = ", ".join(parts) if parts else "no numeric summary available"
    return f"- {name}: {stats_text}."


def _format_categorical_stat(name: str, values: List[Dict[str, float]], limit: int = 3) -> str:
    top_values = values[:limit]
    formatted = ", ".join(
        f"{entry.get('value', 'Unknown')} {entry.get('percentage', 0):.1f}%"
        for entry in top_values
    )
    return f"- {name}: {formatted}."


def build_quantitative_highlights(
    filename: str,
    quant_summary: Optional[Dict[str, any]],
    numeric_limit: int = 3,
    categorical_limit: int = 3,
) -> str:
    """Return markdown bullet points summarising quantitative insights."""

    if not quant_summary:
        return ""

    row_count = quant_summary.get("row_count")
    column_count = quant_summary.get("column_count")
    numeric = select_priority_numeric_columns(
        quant_summary.get("numeric_columns"), numeric_limit
    )
    categorical = select_priority_categorical_columns(
        quant_summary.get("categorical_columns"), categorical_limit
    )

    lines: List[str] = []

    if row_count or column_count:
        participants = f"{row_count:,} respondents" if isinstance(row_count, int) else "unknown sample size"
        fields = (
            f"across {column_count} fields" if isinstance(column_count, int) and column_count else ""
        )
        scope = f"{participants}{' ' + fields if fields else ''}"
        lines.append(f"- Sample scope: {scope.strip()}.")

    for name, stats in numeric.items():
        lines.append(_format_numeric_stat(name, stats))

    for name, values in categorical.items():
        lines.append(_format_categorical_stat(name, values))

    if not lines:
        return ""

    header = f"Key quantitative insights from {filename}:"
    return "\n".join([header, *lines])


__all__ = [
    "build_quantitative_highlights",
    "select_priority_numeric_columns",
    "select_priority_categorical_columns",
]
