"""Prompt templates for Pitch Deck Generator workflow."""

from .pitch_prompts import (
    SYSTEM_PROMPT,
    DECK_INTENT_ROUTER_PROMPT,
    DECK_PLANNER_PROMPT,
    SLIDE_QUERY_BUILDER_PROMPT,
    EVIDENCE_GRADER_PROMPT,
    WEB_RESEARCH_PLANNER_PROMPT,
    WEB_EVIDENCE_EXTRACTOR_PROMPT,
    SLIDE_WRITER_PROMPT,
    CONSISTENCY_CHECK_PROMPT,
)

__all__ = [
    "SYSTEM_PROMPT",
    "DECK_INTENT_ROUTER_PROMPT",
    "DECK_PLANNER_PROMPT",
    "SLIDE_QUERY_BUILDER_PROMPT",
    "EVIDENCE_GRADER_PROMPT",
    "WEB_RESEARCH_PLANNER_PROMPT",
    "WEB_EVIDENCE_EXTRACTOR_PROMPT",
    "SLIDE_WRITER_PROMPT",
    "CONSISTENCY_CHECK_PROMPT",
]
