"use client";

import React, { useMemo, useState, useCallback, useEffect, useRef } from "react";
import { MessageCircle } from "lucide-react";
import { SolutionCriticProps } from './types';
import { useSolutionCritic } from './hooks';
import {
  LoadingState,
  GeneratingState,
  ErrorState,
  EmptyState,
  Header,
  CritiqueCard,
  ResearchSources,
  ChatDrawer,
} from './components';

/**
 * Solution Critic Component
 * Displays AI-powered critique of the user's solution with recommendations
 */
const SolutionCritic: React.FC<SolutionCriticProps> = ({ projectId }) => {
  const {
    data,
    loading,
    error,
    isGoingBack,
    isGenerating,
    isRefreshing,
    isContinueLoading,
    generationProgress,
    handleGoBack,
    handleRefresh,
    generateSolutionCritique,
    stopPolling,
    handleContinue,
  } = useSolutionCritic(projectId);

  // Chat drawer state
  const [isChatOpen, setIsChatOpen] = useState(false);

  // Track if auto-generation has been triggered
  const hasAutoGeneratedRef = useRef(false);

  // Chat handlers
  const openChat = useCallback(() => setIsChatOpen(true), []);
  const closeChat = useCallback(() => setIsChatOpen(false), []);

  // Memoize data derived from the response
  const allCritiques = useMemo(() => {
    let critiques = [...(data?.all_critiques || [])];

    // Reorder "Business Model Defensibility Critique" to be at number 5 (index 4)
    // We check section_name instead of title
    const businessModelIdx = critiques.findIndex(c =>
      c.section_name && c.section_name.toLowerCase().includes("business model defensibility")
    );

    if (businessModelIdx !== -1) {
      const [item] = critiques.splice(businessModelIdx, 1);
      // Insert at index 4 (5th position), or end if length is smaller
      const insertIdx = Math.min(4, critiques.length);
      critiques.splice(insertIdx, 0, item);
    }

    return critiques;
  }, [data]);
  console.log(`allCritiques`, allCritiques)
  const allSources = useMemo(() => data?.sources || [], [data]);
  const critiquesByDimension = useMemo(() => data?.critiques_by_dimension || {}, [data]);

  // Get executive summary data
  const executiveSummary = useMemo(() => data?.executive_summary, [data]);

  // Create map of critique_id to dimension summary for quick lookup
  const critiqueSummaryMap = useMemo(() => {
    const summaryMap: Record<string, string> = {};
    Object.values(critiquesByDimension).forEach((dimension) => {
      if (dimension) {
        dimension.critiques.forEach((critique) => {
          summaryMap[critique.critique_id] = dimension.summary;
        });
      }
    });
    return summaryMap;
  }, [critiquesByDimension]);

  // ============================================
  // Auto-start generation when no data exists
  // ============================================
  useEffect(() => {
    // Only auto-generate if:
    // 1. We have NO_DATA error (no critique exists)
    // 2. Not currently loading, generating, or refreshing
    // 3. Haven't already triggered auto-generation
    if (
      error === 'NO_DATA' &&
      !loading &&
      !isGenerating &&
      !isRefreshing &&
      !hasAutoGeneratedRef.current
    ) {
      if (process.env.NODE_ENV === 'development') {
        console.log('🚀 No solution critique found, automatically starting generation...');
      }

      // Mark that we've triggered auto-generation
      hasAutoGeneratedRef.current = true;

      // Small delay to ensure component is mounted
      const timer = setTimeout(() => {
        generateSolutionCritique();
      }, 500);

      return () => clearTimeout(timer);
    }
  }, [error, loading, isGenerating, isRefreshing, generateSolutionCritique]);

  // ============================================
  // Render: Priority States (Generating > Loading > Error)
  // ============================================

  if (isGenerating) {
    return (
      <GeneratingState
        progress={generationProgress}
        onCancel={() => stopPolling(true)}
      />
    );
  }

  // Check loading OR refreshing to prevent stale UI during manual refresh
  if (loading || isRefreshing) {
    return <LoadingState />;
  }

  if (error) {
    // Handle NO_DATA as empty state (no critique exists yet)
    if (error === 'NO_DATA') {
      return (
        <EmptyState
          onGoBack={handleGoBack}
          onGenerate={generateSolutionCritique}
        />
      );
    }

    return (
      <ErrorState
        error={error}
        onGoBack={handleGoBack}
        onRetry={handleRefresh}
        onGenerate={generateSolutionCritique}
      />
    );
  }

  // ============================================
  // Render: Empty State (no error, not loading, but no data)
  // Only show empty state if we explicitly got NO_DATA error
  // Otherwise show loading (initial fetch in progress)
  // ============================================

  if (!data) {
    // If no data and no error, we're still in initial loading
    return <LoadingState />;
  }

  // ============================================
  // Render: Main Content
  // ============================================

  return (
    <div className="space-y-2">
      {/* Header Section */}
      <Header
        isGoingBack={isGoingBack}
        isGenerating={isGenerating}
        isContinueLoading={isContinueLoading}
        onGoBack={handleGoBack}
        onRegenerate={generateSolutionCritique}
        onContinue={handleContinue}
      />

      {/* Critiques List */}
      <div className="space-y-2 my-4">
        {allCritiques.map((critique, index) => (
          <CritiqueCard
            key={critique.critique_id}
            critique={critique}
            index={index}
            allSources={allSources}
            dimensionSummary={critiqueSummaryMap[critique.critique_id]}
          />
        ))}
      </div>

      {/* Research Sources Section */}
      <ResearchSources sources={allSources} />

      {/* Floating Chat Button */}
      <button
        onClick={openChat}
        className="fixed bottom-6 right-6 z-40 flex h-14 w-14 items-center justify-center rounded-full bg-brand-500 text-white shadow-lg transition-all duration-200 hover:bg-brand-600 hover:scale-110 focus:outline-none focus:ring-2 focus:ring-brand-500 focus:ring-offset-2"
        aria-label="Open chat with Solution Critique AI"
      >
        <MessageCircle className="h-6 w-6" />
      </button>

      {/* Chat Drawer */}
      <ChatDrawer
        isOpen={isChatOpen}
        onClose={closeChat}
        projectId={projectId}
        title="Chat with Solution Critique"
        placeholder="Ask about the critique findings..."
        emptyStateTitle="Ask about the critique"
        emptyStateDescription="Get AI-powered insights about the solution critique, recommendations, and how to improve your solution."
        suggestedQuestions={[
          "What are the key insights from this critique?",
          "What are the highest priority recommendations?",
          "How can I improve my competitive differentiation?",
          "What are the main business model vulnerabilities?"
        ]}
      />
    </div>
  );
};

export default SolutionCritic;