"""
Core data schemas for the MINT multi-agent market intelligence platform.

This module defines all shared types that flow through the system, including:
- GraphState for the LangGraph workflow
- Pydantic models for all data structures
- API request/response models
"""

from enum import Enum
from typing import Dict, List, Optional, Set, TypedDict, Any
from pydantic import BaseModel, Field, HttpUrl
from datetime import datetime, date
import uuid


class JobStatus(str, Enum):
    """Status of a research job."""
    PENDING = "pending"  # Job created but not started
    CLARIFYING = "clarifying"  # Waiting for user input on clarification questions
    RESEARCHING = "researching"  # Active research in progress
    ANALYZING = "analyzing"  # Analyzing research results
    GENERATING = "generating"  # Generating final report
    COMPLETED = "completed"  # Research complete with report
    FAILED = "failed"  # Job failed


class GraphState(TypedDict):
    """
    Represents the state object that flows through the LangGraph workflow.
    
    This state is progressively filled as it moves through the agent nodes.
    """
    initial_query: str  # The original user query
    user_id: str  # Identifier for the user who created the job
    job_id: str  # Unique identifier for the job
    clarification_questions: Optional[List[str]]  # Questions to ask the user
    user_answers: Optional[Dict[str, str]]  # User's answers to clarification questions
    master_specification: Optional[str]  # Comprehensive research specification
    extracted_metadata: Optional[Dict[str, Any]]  # Parsed metadata from the master prompt
    industry_specification: Optional[str]  # Specification for industry research
    pestel_specification: Optional[str]  # Specification for PESTLE analysis
    industry_report_uri: Optional[str]  # URI to the industry analysis report
    pestel_report_uri: Optional[str]  # URI to the PESTLE analysis report
    recommendations: Optional[Dict[str, Any]]  # Synthesized recommendations
    final_report_uri: Optional[str]  # URI to the final markdown report
    cited_sources: Set[str]  # Set of all sources cited in the research


class Fact(BaseModel):
    """
    A single factual statement extracted from research.
    
    Each fact is tied to its source for verification.
    """
    content: str = Field(..., description="The factual statement")
    source_url: HttpUrl = Field(..., description="URL where the fact was found")
    source_title: Optional[str] = Field(None, description="Title of the source")
    confidence: Optional[float] = Field(None, description="Confidence score of the fact (0.0-1.0)", ge=0.0, le=1.0)
    category: str = Field(..., description="Category the fact belongs to (e.g., 'Market Size', 'Regulation')")
    extracted_at: Optional[str] = Field(None, description="ISO timestamp when the fact was extracted")


class ResearchSpec(BaseModel):
    """
    Specification for a research subtask.
    
    Used to guide the research agents in their information gathering.
    """
    title: str = Field(..., description="Title of the research specification")
    description: str = Field(..., description="Detailed description of research goals")
    key_questions: List[str] = Field(..., description="Key questions to answer")
    required_fact_categories: List[str] = Field(..., description="Categories of facts that must be found")
    geography_focus: List[str] = Field(..., description="Geographic regions to focus on")
    industry_focus: List[str] = Field(..., description="Industries to focus on")
    keywords: List[str] = Field(..., description="Key terms for search optimization")


class MiniReport(BaseModel):
    """
    A structured sub-report generated by a research agent.
    
    These are later synthesized into the final report.
    """
    title: str = Field(..., description="Title of the report section")
    summary: str = Field(..., description="Executive summary of findings")
    facts: List[Fact] = Field(..., description="Supporting facts with citations")
    sections: Dict[str, List[Fact]] = Field(..., description="Organized facts by section")
    gaps: List[str] = Field([], description="Identified information gaps")
    uri: Optional[str] = Field(None, description="Storage URI for this report")


class Recommendation(BaseModel):
    """
    A strategic recommendation based on research findings.
    
    Generated by the recommendation agent based on analysis results.
    """
    content: str = Field(..., description="The recommendation text")
    category: str = Field(..., description="Category of the recommendation (e.g. 'Business Model', 'Marketing')")
    priority: int = Field(..., description="Priority level (1-3, where 1 is highest)", ge=1, le=3)
    supporting_facts: List[str] = Field(..., description="IDs of facts supporting this recommendation")
    impact: Optional[float] = Field(None, description="Estimated impact score (0.0-1.0)", ge=0.0, le=1.0)
    implementation_complexity: Optional[float] = Field(None, description="Complexity of implementation (0.0-1.0)", ge=0.0, le=1.0)
    timeframe: Optional[str] = Field(None, description="Suggested timeframe for implementation")


class Job(BaseModel):
    """
    A market research job.
    
    Tracks the complete lifecycle of a research request.
    """
    job_id: str = Field(..., description="Unique identifier for the job")
    user_id: str = Field(..., description="ID of the user who created the job")
    initial_query: str = Field(..., description="The original user query")
    status: JobStatus = Field(default=JobStatus.PENDING, description="Current status of the job")
    created_at: str = Field(..., description="ISO timestamp when job was created")
    updated_at: str = Field(..., description="ISO timestamp when job was last updated")
    clarification_questions: Optional[List[str]] = Field(None, description="Questions asked to the user")
    final_report_uri: Optional[str] = Field(None, description="URI to the final report when completed")
    error: Optional[str] = Field(None, description="Error message if job failed")


# API Request/Response Models

class CreateJobRequest(BaseModel):
    """Request to create a new research job."""
    query: str = Field(..., min_length=10, description="Problem statement to research")
    user_id: str = Field(..., description="User identifier")


class CreateJobResponse(BaseModel):
    """Response after creating a new job."""
    job_id: str = Field(..., description="Unique identifier for the created job")
    status: JobStatus = Field(..., description="Initial status of the job")
    clarification_questions: Optional[List[str]] = Field(None, description="Questions if already generated")


class SubmitClarificationRequest(BaseModel):
    """Request to submit answers to clarification questions."""
    job_id: str = Field(..., description="Job identifier")
    user_id: str = Field(..., description="User identifier")
    answers: Dict[str, str] = Field(..., description="Answers to clarification questions")


# Admin Dashboard Models

class AuditLogAction(str, Enum):
    """Types of admin actions that can be logged."""
    USER_SUSPEND = "user_suspend"
    USER_ACTIVATE = "user_activate"
    USER_PASSWORD_RESET = "user_password_reset"
    USER_ROLE_ADD = "user_role_add"
    USER_ROLE_REMOVE = "user_role_remove"
    SESSION_TERMINATE = "session_terminate"
    CONFIG_UPDATE = "config_update"
    SYSTEM_MAINTENANCE = "system_maintenance"
    REPORT_DELETE = "report_delete"
    BULK_OPERATION = "bulk_operation"


class AuditLogTargetType(str, Enum):
    """Types of targets that can be affected by admin actions."""
    USER = "user"
    SYSTEM = "system"
    REPORT = "report"
    SESSION = "session"
    CONFIG = "config"


class AuditLog(BaseModel):
    """Audit log entry for administrative actions."""
    id: Optional[str] = Field(default_factory=lambda: str(uuid.uuid4()), description="Unique identifier")
    timestamp: datetime = Field(default_factory=datetime.utcnow, description="When the action occurred")
    admin_user_id: str = Field(..., description="ID of the admin who performed the action")
    action: AuditLogAction = Field(..., description="Type of action performed")
    target_type: AuditLogTargetType = Field(..., description="Type of target affected")
    target_id: Optional[str] = Field(None, description="ID of the specific target")
    details: Dict[str, Any] = Field(default_factory=dict, description="Additional context and metadata")
    ip_address: Optional[str] = Field(None, description="IP address of the admin")
    user_agent: Optional[str] = Field(None, description="User agent string")
    success: bool = Field(default=True, description="Whether the action was successful")
    error_message: Optional[str] = Field(None, description="Error message if action failed")
    created_at: datetime = Field(default_factory=datetime.utcnow, description="Record creation timestamp")


class AuditLogCreate(BaseModel):
    """Request to create an audit log entry."""
    admin_user_id: str = Field(..., description="ID of the admin performing the action")
    action: AuditLogAction = Field(..., description="Type of action being performed")
    target_type: AuditLogTargetType = Field(..., description="Type of target being affected")
    target_id: Optional[str] = Field(None, description="ID of the specific target")
    details: Dict[str, Any] = Field(default_factory=dict, description="Additional context")
    ip_address: Optional[str] = Field(None, description="IP address of the admin")
    user_agent: Optional[str] = Field(None, description="User agent string")
    success: bool = Field(default=True, description="Whether the action was successful")
    error_message: Optional[str] = Field(None, description="Error message if action failed")


class AuditLogQuery(BaseModel):
    """Query parameters for retrieving audit logs."""
    limit: int = Field(default=50, ge=1, le=1000, description="Maximum number of logs to return")
    offset: int = Field(default=0, ge=0, description="Number of logs to skip")
    admin_user_id: Optional[str] = Field(None, description="Filter by admin user ID")
    action: Optional[AuditLogAction] = Field(None, description="Filter by action type")
    target_type: Optional[AuditLogTargetType] = Field(None, description="Filter by target type")
    start_date: Optional[datetime] = Field(None, description="Filter logs after this date")
    end_date: Optional[datetime] = Field(None, description="Filter logs before this date")
    success: Optional[bool] = Field(None, description="Filter by success status")


class AuditLogResponse(BaseModel):
    """Response containing audit log entries."""
    logs: List[AuditLog] = Field(..., description="List of audit log entries")
    total_count: int = Field(..., description="Total number of matching logs")
    has_more: bool = Field(..., description="Whether there are more logs available")


class AuditLogStats(BaseModel):
    """Statistics about audit log entries."""
    total_actions: int = Field(..., description="Total number of actions in period")
    successful_actions: int = Field(..., description="Number of successful actions")
    failed_actions: int = Field(..., description="Number of failed actions")
    unique_admins: int = Field(..., description="Number of unique admins who performed actions")
    most_common_action: str = Field(..., description="Most frequently performed action")
    action_count: int = Field(..., description="Count of the most common action")


# System Metrics Models

class MetricType(str, Enum):
    """Types of system metrics."""
    INFRASTRUCTURE = "infrastructure"
    API = "api"
    AGENT = "agent"
    QUEUE = "queue"
    DATABASE = "database"


class SystemMetric(BaseModel):
    """A system performance metric."""
    id: Optional[str] = Field(default_factory=lambda: str(uuid.uuid4()), description="Unique identifier")
    timestamp: datetime = Field(default_factory=datetime.utcnow, description="When the metric was recorded")
    metric_type: MetricType = Field(..., description="Category of the metric")
    metric_name: str = Field(..., description="Specific metric name")
    value: float = Field(..., description="Metric value")
    unit: Optional[str] = Field(None, description="Unit of measurement")
    tags: Dict[str, Any] = Field(default_factory=dict, description="Additional metadata")
    source: Optional[str] = Field(None, description="Source system or component")
    created_at: datetime = Field(default_factory=datetime.utcnow, description="Record creation timestamp")


class SystemMetricCreate(BaseModel):
    """Request to create a system metric."""
    metric_type: MetricType = Field(..., description="Category of the metric")
    metric_name: str = Field(..., description="Specific metric name")
    value: float = Field(..., description="Metric value")
    unit: Optional[str] = Field(None, description="Unit of measurement")
    tags: Dict[str, Any] = Field(default_factory=dict, description="Additional metadata")
    source: Optional[str] = Field(None, description="Source system or component")


class AgentStatus(str, Enum):
    """Status of an agent."""
    ACTIVE = "active"
    IDLE = "idle"
    ERROR = "error"
    MAINTENANCE = "maintenance"


class AgentStatusRecord(BaseModel):
    """Status record for an agent."""
    id: Optional[str] = Field(default_factory=lambda: str(uuid.uuid4()), description="Unique identifier")
    agent_name: str = Field(..., description="Name of the agent")
    status: AgentStatus = Field(default=AgentStatus.IDLE, description="Current status")
    last_execution: Optional[datetime] = Field(None, description="Last execution time")
    last_success: Optional[datetime] = Field(None, description="Last successful execution")
    last_error: Optional[datetime] = Field(None, description="Last error time")
    success_rate: float = Field(default=0.0, description="Success rate percentage")
    average_execution_time: float = Field(default=0.0, description="Average execution time in milliseconds")
    total_executions: int = Field(default=0, description="Total number of executions")
    successful_executions: int = Field(default=0, description="Number of successful executions")
    failed_executions: int = Field(default=0, description="Number of failed executions")
    current_job_id: Optional[str] = Field(None, description="Current job being processed")
    error_message: Optional[str] = Field(None, description="Last error message")
    performance_metrics: Dict[str, Any] = Field(default_factory=dict, description="Detailed performance data")
    health_check_at: datetime = Field(default_factory=datetime.utcnow, description="Last health check time")
    created_at: datetime = Field(default_factory=datetime.utcnow, description="Record creation time")
    updated_at: datetime = Field(default_factory=datetime.utcnow, description="Last update time")


class AgentStatusUpdate(BaseModel):
    """Request to update agent status."""
    agent_name: str = Field(..., description="Name of the agent")
    status: Optional[AgentStatus] = Field(None, description="New status")
    execution_time: Optional[float] = Field(None, description="Execution time in milliseconds")
    success: Optional[bool] = Field(None, description="Whether the execution was successful")
    job_id: Optional[str] = Field(None, description="Job ID being processed")
    error_message: Optional[str] = Field(None, description="Error message if failed")
    performance_metrics: Optional[Dict[str, Any]] = Field(None, description="Performance data")


class APIHealthRecord(BaseModel):
    """Health check record for an external API."""
    id: Optional[str] = Field(default_factory=lambda: str(uuid.uuid4()), description="Unique identifier")
    api_name: str = Field(..., description="Name of the API")
    endpoint: str = Field(..., description="API endpoint checked")
    status_code: Optional[int] = Field(None, description="HTTP status code")
    response_time: Optional[float] = Field(None, description="Response time in milliseconds")
    success: bool = Field(default=False, description="Whether the check was successful")
    error_message: Optional[str] = Field(None, description="Error message if failed")
    checked_at: datetime = Field(default_factory=datetime.utcnow, description="When the check was performed")
    created_at: datetime = Field(default_factory=datetime.utcnow, description="Record creation time")


class APIHealthCheck(BaseModel):
    """Request to record an API health check."""
    api_name: str = Field(..., description="Name of the API")
    endpoint: str = Field(..., description="API endpoint to check")
    status_code: Optional[int] = Field(None, description="HTTP status code")
    response_time: Optional[float] = Field(None, description="Response time in milliseconds")
    success: bool = Field(default=False, description="Whether the check was successful")
    error_message: Optional[str] = Field(None, description="Error message if failed")


class MetricsQuery(BaseModel):
    """Query parameters for retrieving metrics."""
    metric_type: Optional[MetricType] = Field(None, description="Filter by metric type")
    metric_name: Optional[str] = Field(None, description="Filter by metric name")
    start_date: Optional[datetime] = Field(None, description="Start of time range")
    end_date: Optional[datetime] = Field(None, description="End of time range")
    interval: str = Field(default="1 hour", description="Aggregation interval")


class MetricsAggregated(BaseModel):
    """Aggregated metrics data."""
    time_bucket: datetime = Field(..., description="Time bucket for aggregation")
    metric_type: str = Field(..., description="Type of metric")
    metric_name: str = Field(..., description="Name of metric")
    avg_value: float = Field(..., description="Average value in time bucket")
    min_value: float = Field(..., description="Minimum value in time bucket")
    max_value: float = Field(..., description="Maximum value in time bucket")
    count_values: int = Field(..., description="Number of values in time bucket")


class AgentStatusSummary(BaseModel):
    """Summary of all agent statuses."""
    total_agents: int = Field(..., description="Total number of agents")
    active_agents: int = Field(..., description="Number of active agents")
    idle_agents: int = Field(..., description="Number of idle agents")
    error_agents: int = Field(..., description="Number of agents in error state")
    avg_success_rate: float = Field(..., description="Average success rate across all agents")
    avg_execution_time: float = Field(..., description="Average execution time across all agents")


class APIHealthSummary(BaseModel):
    """Summary of API health status."""
    api_name: str = Field(..., description="Name of the API")
    total_checks: int = Field(..., description="Total number of health checks")
    successful_checks: int = Field(..., description="Number of successful checks")
    failed_checks: int = Field(..., description="Number of failed checks")
    success_rate: float = Field(..., description="Success rate percentage")
    avg_response_time: Optional[float] = Field(None, description="Average response time")
    last_check: Optional[datetime] = Field(None, description="Last check time")
    last_success: Optional[datetime] = Field(None, description="Last successful check time")
    current_status: str = Field(..., description="Current health status")


# User Analytics Models

class UserProfile(BaseModel):
    """Extended user profile with analytics data."""
    id: str = Field(..., description="User ID")
    email: Optional[str] = Field(None, description="User email")
    display_name: Optional[str] = Field(None, description="Display name")
    avatar_url: Optional[str] = Field(None, description="Avatar URL")
    created_at: datetime = Field(..., description="Account creation date")
    updated_at: datetime = Field(..., description="Last profile update")
    last_login: Optional[datetime] = Field(None, description="Last login time")
    last_activity: Optional[datetime] = Field(None, description="Last activity time")
    login_count: int = Field(default=0, description="Total number of logins")
    total_requests: int = Field(default=0, description="Total API requests made")
    total_reports_generated: int = Field(default=0, description="Total reports generated")
    total_screen_time_minutes: int = Field(default=0, description="Total screen time in minutes")
    subscription_status: str = Field(default="free", description="Subscription status")
    subscription_start_date: Optional[datetime] = Field(None, description="Subscription start date")
    subscription_end_date: Optional[datetime] = Field(None, description="Subscription end date")
    geographic_location: Optional[str] = Field(None, description="Geographic location")
    timezone: Optional[str] = Field(None, description="User timezone")
    usage_analytics: Dict[str, Any] = Field(default_factory=dict, description="Additional usage analytics")
    engagement_score: float = Field(default=0.0, description="Calculated engagement score (0-100)")
    preferences: Dict[str, Any] = Field(default_factory=dict, description="User preferences")


class UserAnalyticsSummary(BaseModel):
    """Summary analytics for a user."""
    user_id: str = Field(..., description="User ID")
    email: Optional[str] = Field(None, description="User email")
    display_name: Optional[str] = Field(None, description="Display name")
    created_at: datetime = Field(..., description="Account creation date")
    last_login: Optional[datetime] = Field(None, description="Last login time")
    last_activity: Optional[datetime] = Field(None, description="Last activity time")
    login_count: int = Field(..., description="Total number of logins")
    total_requests: int = Field(..., description="Total API requests made")
    total_reports_generated: int = Field(..., description="Total reports generated")
    total_screen_time_minutes: int = Field(..., description="Total screen time in minutes")
    subscription_status: str = Field(..., description="Subscription status")
    geographic_location: Optional[str] = Field(None, description="Geographic location")
    engagement_score: float = Field(..., description="Calculated engagement score")
    days_since_signup: int = Field(..., description="Days since account creation")
    avg_requests_per_day: float = Field(..., description="Average requests per day")
    avg_reports_per_day: float = Field(..., description="Average reports per day")


class UserActivityType(str, Enum):
    """Types of user activities that can be logged."""
    LOGIN = "login"
    LOGOUT = "logout"
    REQUEST = "request"
    REPORT_GENERATED = "report_generated"
    PAGE_VIEW = "page_view"
    SCREEN_TIME = "screen_time"


class UserActivityLog(BaseModel):
    """User activity log entry."""
    id: Optional[str] = Field(default_factory=lambda: str(uuid.uuid4()), description="Unique identifier")
    user_id: str = Field(..., description="User ID")
    activity_type: UserActivityType = Field(..., description="Type of activity")
    activity_data: Dict[str, Any] = Field(default_factory=dict, description="Activity-specific data")
    session_id: Optional[str] = Field(None, description="Session identifier")
    ip_address: Optional[str] = Field(None, description="IP address")
    user_agent: Optional[str] = Field(None, description="User agent string")
    timestamp: datetime = Field(default_factory=datetime.utcnow, description="Activity timestamp")
    created_at: datetime = Field(default_factory=datetime.utcnow, description="Record creation time")


class UserAnalyticsQuery(BaseModel):
    """Query parameters for user analytics."""
    limit: int = Field(default=50, ge=1, le=1000, description="Maximum number of users to return")
    offset: int = Field(default=0, ge=0, description="Number of users to skip")
    order_by: str = Field(default="last_activity", description="Field to order by")
    order_direction: str = Field(default="DESC", description="Order direction (ASC/DESC)")
    subscription_status: Optional[str] = Field(None, description="Filter by subscription status")
    min_engagement_score: Optional[float] = Field(None, description="Minimum engagement score")
    geographic_location: Optional[str] = Field(None, description="Filter by location")


class UserAnalyticsResponse(BaseModel):
    """Response containing user analytics data."""
    users: List[UserAnalyticsSummary] = Field(..., description="List of user analytics")
    total_count: int = Field(..., description="Total number of matching users")
    has_more: bool = Field(..., description="Whether there are more users available")


class UserActivityTimelineQuery(BaseModel):
    """Query parameters for user activity timeline."""
    user_id: str = Field(..., description="User ID")
    limit: int = Field(default=100, ge=1, le=1000, description="Maximum number of activities to return")
    activity_types: Optional[List[UserActivityType]] = Field(None, description="Filter by activity types")


class UserAnalyticsAggregated(BaseModel):
    """Aggregated user analytics data."""
    time_bucket: datetime = Field(..., description="Time bucket for aggregation")
    new_users: int = Field(..., description="Number of new users in period")
    active_users: int = Field(..., description="Number of active users in period")
    total_logins: int = Field(..., description="Total logins in period")
    total_requests: int = Field(..., description="Total requests in period")
    total_reports: int = Field(..., description="Total reports generated in period")
    avg_engagement_score: Optional[float] = Field(None, description="Average engagement score in period")


class UserAnalyticsAggregatedQuery(BaseModel):
    """Query parameters for aggregated user analytics."""
    start_date: Optional[datetime] = Field(None, description="Start of time range")
    end_date: Optional[datetime] = Field(None, description="End of time range")
    interval: str = Field(default="1 day", description="Aggregation interval")


class UserLoginAnalytics(BaseModel):
    """Request to update user login analytics."""
    user_id: str = Field(..., description="User ID")
    ip_address: Optional[str] = Field(None, description="IP address")
    user_agent: Optional[str] = Field(None, description="User agent string")
    session_id: Optional[str] = Field(None, description="Session identifier")


class UserRequestAnalytics(BaseModel):
    """Request to update user request analytics."""
    user_id: str = Field(..., description="User ID")
    request_type: str = Field(default="general", description="Type of request")
    request_data: Dict[str, Any] = Field(default_factory=dict, description="Request-specific data")
    session_id: Optional[str] = Field(None, description="Session identifier")


class UserReportAnalytics(BaseModel):
    """Request to update user report generation analytics."""
    user_id: str = Field(..., description="User ID")
    report_type: str = Field(default="general", description="Type of report")
    report_data: Dict[str, Any] = Field(default_factory=dict, description="Report-specific data")
    session_id: Optional[str] = Field(None, description="Session identifier")


class UserScreenTimeAnalytics(BaseModel):
    """Request to update user screen time analytics."""
    user_id: str = Field(..., description="User ID")
    session_duration_minutes: int = Field(..., ge=0, description="Session duration in minutes")
    session_id: Optional[str] = Field(None, description="Session identifier")


# User Engagement Models

class EngagementEventType(str, Enum):
    """Types of user engagement events."""
    CLICK = "click"
    SCROLL = "scroll"
    HOVER = "hover"
    FOCUS = "focus"
    BLUR = "blur"
    DOWNLOAD = "download"
    SHARE = "share"
    PAGE_VIEW = "page_view"


class EngagementEventCategory(str, Enum):
    """Categories of engagement events."""
    NAVIGATION = "navigation"
    CONTENT = "content"
    ACTION = "action"
    REPORT = "report"
    LINK = "link"


class UserEngagementEvent(BaseModel):
    """User engagement event record."""
    id: Optional[str] = Field(default_factory=lambda: str(uuid.uuid4()), description="Unique identifier")
    user_id: str = Field(..., description="User ID")
    event_type: EngagementEventType = Field(..., description="Type of engagement event")
    event_category: EngagementEventCategory = Field(..., description="Category of the event")
    event_label: Optional[str] = Field(None, description="Specific element or action identifier")
    event_value: Optional[float] = Field(None, description="Optional numeric value")
    page_url: Optional[str] = Field(None, description="URL of the page")
    page_title: Optional[str] = Field(None, description="Title of the page")
    element_id: Optional[str] = Field(None, description="DOM element ID")
    element_class: Optional[str] = Field(None, description="DOM element class")
    element_text: Optional[str] = Field(None, description="Text content of element")
    session_id: Optional[str] = Field(None, description="Session identifier")
    timestamp: datetime = Field(default_factory=datetime.utcnow, description="Event timestamp")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Additional event data")
    created_at: datetime = Field(default_factory=datetime.utcnow, description="Record creation time")


class UserEngagementEventCreate(BaseModel):
    """Request to create a user engagement event."""
    user_id: str = Field(..., description="User ID")
    event_type: EngagementEventType = Field(..., description="Type of engagement event")
    event_category: EngagementEventCategory = Field(..., description="Category of the event")
    event_label: Optional[str] = Field(None, description="Specific element or action identifier")
    event_value: Optional[float] = Field(None, description="Optional numeric value")
    page_url: Optional[str] = Field(None, description="URL of the page")
    page_title: Optional[str] = Field(None, description="Title of the page")
    element_id: Optional[str] = Field(None, description="DOM element ID")
    element_class: Optional[str] = Field(None, description="DOM element class")
    element_text: Optional[str] = Field(None, description="Text content of element")
    session_id: Optional[str] = Field(None, description="Session identifier")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Additional event data")


# Export Models

class EngagementExportFormat(str, Enum):
    """Supported export formats for engagement data."""
    CSV = "csv"
    JSON = "json"
    PDF = "pdf"
    EXCEL = "excel"


class EngagementExportRequest(BaseModel):
    """Request to export engagement analytics data."""
    format: EngagementExportFormat = Field(..., description="Export format")
    start_date: date = Field(..., description="Start date for data export")
    end_date: date = Field(..., description="End date for data export")
    include_sessions: bool = Field(default=False, description="Include detailed session data")
    include_events: bool = Field(default=False, description="Include individual event data")
    email_delivery: bool = Field(default=False, description="Send export via email")
    email_recipients: List[str] = Field(default_factory=list, description="Email recipients for delivery")
    filters: Dict[str, Any] = Field(default_factory=dict, description="Additional filters")


class EngagementExportResult(BaseModel):
    """Result of an engagement data export."""
    format: EngagementExportFormat = Field(..., description="Export format used")
    filename: str = Field(..., description="Generated filename")
    content: bytes = Field(..., description="Export file content")
    content_type: str = Field(..., description="MIME content type")
    size: int = Field(..., description="File size in bytes")
    generated_at: datetime = Field(..., description="Export generation timestamp")
    download_url: Optional[str] = Field(None, description="Temporary download URL")


class ExportFormat(str, Enum):
    """Supported export formats for admin data."""
    CSV = "csv"
    JSON = "json"
    PDF = "pdf"
    EXCEL = "excel"


class DataExportRequest(BaseModel):
    """Request to export admin dashboard data."""
    data_type: str = Field(..., description="Type of data to export (users, metrics, audit_logs, etc.)")
    format: ExportFormat = Field(..., description="Export format")
    start_date: Optional[date] = Field(None, description="Start date for data export")
    end_date: Optional[date] = Field(None, description="End date for data export")
    filters: Dict[str, Any] = Field(default_factory=dict, description="Additional filters")
    include_charts: bool = Field(default=False, description="Include charts in PDF exports")
    email_delivery: bool = Field(default=False, description="Send export via email")
    email_recipients: List[str] = Field(default_factory=list, description="Email recipients for delivery")


class DataExportResult(BaseModel):
    """Result of a data export operation."""
    export_id: str = Field(..., description="Unique export identifier")
    data_type: str = Field(..., description="Type of data exported")
    format: ExportFormat = Field(..., description="Export format used")
    filename: str = Field(..., description="Generated filename")
    content: bytes = Field(..., description="Export file content")
    content_type: str = Field(..., description="MIME content type")
    size: int = Field(..., description="File size in bytes")
    generated_at: datetime = Field(..., description="Export generation timestamp")
    download_url: Optional[str] = Field(None, description="Temporary download URL")
    email_sent: bool = Field(default=False, description="Whether email was sent successfully")


class ScheduledReportConfig(BaseModel):
    """Configuration for scheduled reports."""
    name: str = Field(..., description="Report name")
    description: Optional[str] = Field(None, description="Report description")
    data_type: str = Field(..., description="Type of data to export")
    format: ExportFormat = Field(..., description="Export format")
    schedule_cron: str = Field(..., description="Cron expression for schedule")
    email_recipients: List[str] = Field(..., description="Email recipients")
    filters: Dict[str, Any] = Field(default_factory=dict, description="Data filters")
    include_charts: bool = Field(default=False, description="Include charts in reports")
    active: bool = Field(default=True, description="Whether schedule is active")


class ScheduledReport(BaseModel):
    """Scheduled report record."""
    id: str = Field(..., description="Unique identifier")
    config: ScheduledReportConfig = Field(..., description="Report configuration")
    created_by: str = Field(..., description="User who created the schedule")
    created_at: datetime = Field(..., description="Creation timestamp")
    updated_at: datetime = Field(..., description="Last update timestamp")
    last_run: Optional[datetime] = Field(None, description="Last execution time")
    next_run: Optional[datetime] = Field(None, description="Next scheduled execution")
    run_count: int = Field(default=0, description="Number of times executed")
    last_status: Optional[str] = Field(None, description="Status of last execution")
    event_value: Optional[float] = Field(None, description="Optional numeric value")
    page_url: Optional[str] = Field(None, description="URL of the page")
    page_title: Optional[str] = Field(None, description="Title of the page")
    element_id: Optional[str] = Field(None, description="DOM element ID")
    element_class: Optional[str] = Field(None, description="DOM element class")
    element_text: Optional[str] = Field(None, description="Text content of element")
    session_id: Optional[str] = Field(None, description="Session identifier")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Additional event data")


class UserSessionAnalytics(BaseModel):
    """User session analytics record."""
    id: Optional[str] = Field(default_factory=lambda: str(uuid.uuid4()), description="Unique identifier")
    user_id: str = Field(..., description="User ID")
    session_id: str = Field(..., description="Session identifier")
    session_start: datetime = Field(..., description="Session start time")
    session_end: Optional[datetime] = Field(None, description="Session end time")
    duration_minutes: float = Field(default=0.0, description="Session duration in minutes")
    page_views: int = Field(default=0, description="Number of page views")
    unique_pages: int = Field(default=0, description="Number of unique pages visited")
    clicks_count: int = Field(default=0, description="Number of clicks")
    scrolls_count: int = Field(default=0, description="Number of scroll events")
    reports_generated: int = Field(default=0, description="Number of reports generated")
    links_clicked: int = Field(default=0, description="Number of links clicked")
    downloads_count: int = Field(default=0, description="Number of downloads")
    bounce_rate: float = Field(default=0.0, description="Bounce rate (0-1)")
    engagement_score: float = Field(default=0.0, description="Session engagement score")
    entry_page: Optional[str] = Field(None, description="Entry page URL")
    exit_page: Optional[str] = Field(None, description="Exit page URL")
    referrer: Optional[str] = Field(None, description="Referrer URL")
    user_agent: Optional[str] = Field(None, description="User agent string")
    ip_address: Optional[str] = Field(None, description="IP address")
    device_type: Optional[str] = Field(None, description="Device type")
    browser: Optional[str] = Field(None, description="Browser name")
    os: Optional[str] = Field(None, description="Operating system")
    screen_resolution: Optional[str] = Field(None, description="Screen resolution")
    session_data: Dict[str, Any] = Field(default_factory=dict, description="Additional session data")
    created_at: datetime = Field(default_factory=datetime.utcnow, description="Record creation time")
    updated_at: datetime = Field(default_factory=datetime.utcnow, description="Last update time")


class UserSessionAnalyticsUpdate(BaseModel):
    """Request to update user session analytics."""
    user_id: str = Field(..., description="User ID")
    session_id: str = Field(..., description="Session identifier")
    session_start: Optional[datetime] = Field(None, description="Session start time")
    session_end: Optional[datetime] = Field(None, description="Session end time")
    page_view: bool = Field(default=False, description="Whether this is a page view")
    unique_page: Optional[str] = Field(None, description="Unique page URL")
    click: bool = Field(default=False, description="Whether this is a click event")
    scroll: bool = Field(default=False, description="Whether this is a scroll event")
    report_generated: bool = Field(default=False, description="Whether a report was generated")
    link_clicked: bool = Field(default=False, description="Whether a link was clicked")
    download: bool = Field(default=False, description="Whether a download occurred")
    entry_page: Optional[str] = Field(None, description="Entry page URL")
    exit_page: Optional[str] = Field(None, description="Exit page URL")
    referrer: Optional[str] = Field(None, description="Referrer URL")
    user_agent: Optional[str] = Field(None, description="User agent string")
    ip_address: Optional[str] = Field(None, description="IP address")
    device_info: Dict[str, Any] = Field(default_factory=dict, description="Device information")


class EngagementMetricsDaily(BaseModel):
    """Daily aggregated engagement metrics."""
    id: Optional[str] = Field(default_factory=lambda: str(uuid.uuid4()), description="Unique identifier")
    date: datetime = Field(..., description="Date of metrics")
    total_users: int = Field(default=0, description="Total users")
    active_users: int = Field(default=0, description="Active users")
    new_users: int = Field(default=0, description="New users")
    returning_users: int = Field(default=0, description="Returning users")
    total_sessions: int = Field(default=0, description="Total sessions")
    total_page_views: int = Field(default=0, description="Total page views")
    total_clicks: int = Field(default=0, description="Total clicks")
    total_reports_generated: int = Field(default=0, description="Total reports generated")
    total_links_clicked: int = Field(default=0, description="Total links clicked")
    avg_session_duration: float = Field(default=0.0, description="Average session duration")
    avg_pages_per_session: float = Field(default=0.0, description="Average pages per session")
    avg_clicks_per_session: float = Field(default=0.0, description="Average clicks per session")
    bounce_rate: float = Field(default=0.0, description="Bounce rate")
    avg_engagement_score: float = Field(default=0.0, description="Average engagement score")
    top_pages: List[Dict[str, Any]] = Field(default_factory=list, description="Top pages by views")
    top_events: List[Dict[str, Any]] = Field(default_factory=list, description="Top events by count")
    device_breakdown: Dict[str, int] = Field(default_factory=dict, description="Device type breakdown")
    browser_breakdown: Dict[str, int] = Field(default_factory=dict, description="Browser breakdown")
    created_at: datetime = Field(default_factory=datetime.utcnow, description="Record creation time")
    updated_at: datetime = Field(default_factory=datetime.utcnow, description="Last update time")


class EngagementOverview(BaseModel):
    """Engagement overview metrics."""
    total_users: int = Field(..., description="Total users")
    active_users: int = Field(..., description="Active users")
    new_users: int = Field(..., description="New users")
    total_sessions: int = Field(..., description="Total sessions")
    avg_session_duration: float = Field(..., description="Average session duration")
    total_page_views: int = Field(..., description="Total page views")
    avg_pages_per_session: float = Field(..., description="Average pages per session")
    total_clicks: int = Field(..., description="Total clicks")
    total_reports_generated: int = Field(..., description="Total reports generated")
    total_links_clicked: int = Field(..., description="Total links clicked")
    avg_engagement_score: float = Field(..., description="Average engagement score")
    bounce_rate: float = Field(..., description="Bounce rate")


class EngagementTrend(BaseModel):
    """Engagement trend data point."""
    time_bucket: datetime = Field(..., description="Time bucket")
    active_users: int = Field(..., description="Active users")
    total_sessions: int = Field(..., description="Total sessions")
    avg_session_duration: float = Field(..., description="Average session duration")
    total_page_views: int = Field(..., description="Total page views")
    total_clicks: int = Field(..., description="Total clicks")
    total_reports: int = Field(..., description="Total reports")
    avg_engagement_score: float = Field(..., description="Average engagement score")


class EngagementQuery(BaseModel):
    """Query parameters for engagement data."""
    start_date: Optional[datetime] = Field(None, description="Start date")
    end_date: Optional[datetime] = Field(None, description="End date")
    interval: str = Field(default="1 day", description="Time interval")
    user_id: Optional[str] = Field(None, description="Filter by user ID")
    session_id: Optional[str] = Field(None, description="Filter by session ID")
    event_type: Optional[EngagementEventType] = Field(None, description="Filter by event type")
    event_category: Optional[EngagementEventCategory] = Field(None, description="Filter by event category")
