"""GTM Prompt Templates"""

from .gtm_prompts import (
    SYSTEM_PROMPT,
    GTM_PLANNER_PROMPT,
    STEP_SPEC_BUILDER_PROMPT,
    RETRIEVAL_QUERY_BUILDER_PROMPT,
    EVIDENCE_GRADER_PROMPT,
    WEB_RESEARCH_PLANNER_PROMPT,
    WEB_EVIDENCE_EXTRACTOR_PROMPT,
    STEP_WRITER_PROMPT,
    CROSS_STEP_CONSISTENCY_PROMPT,
    ASSEMBLER_PROMPT,
)

__all__ = [
    "SYSTEM_PROMPT",
    "GTM_PLANNER_PROMPT",
    "STEP_SPEC_BUILDER_PROMPT",
    "RETRIEVAL_QUERY_BUILDER_PROMPT",
    "EVIDENCE_GRADER_PROMPT",
    "WEB_RESEARCH_PLANNER_PROMPT",
    "WEB_EVIDENCE_EXTRACTOR_PROMPT",
    "STEP_WRITER_PROMPT",
    "CROSS_STEP_CONSISTENCY_PROMPT",
    "ASSEMBLER_PROMPT",
]
