"""
Transaction-safe billing operations using raw SQL.
These methods wrap critical multi-step operations in database transactions.
"""

import logging
from datetime import datetime
from typing import Dict, Any, List, Optional
from uuid import uuid4
import psycopg2
from psycopg2.extensions import connection as PgConnection

logger = logging.getLogger(__name__)


def create_invoice_with_stripe_atomic(
    conn: PgConnection,
    tenant_id: str,
    period_start: datetime,
    period_end: datetime,
    credits_allocated: int,
    admin_seat_charges: int,
    total_amount_credits: int,
    admin_seats_count: int,
    members_count: int,
    stripe_invoice_id: str,
    stripe_invoice_number: str,
    stripe_hosted_url: str,
    stripe_pdf_url: str,
    tenant_name: str,
    line_items: List[Dict[str, Any]]
) -> Dict[str, Any]:
    """
    Atomically create invoice with line items and Stripe details.
    Uses raw SQL within a transaction.

    Args:
        conn: PostgreSQL connection (must be in transaction)
        tenant_id: Organization ID
        period_start/end: Billing period
        credits_allocated: Credits allocated during period
        admin_seat_charges: Admin seat charges
        total_amount_credits: Total amount
        admin_seats_count: Number of admin seats
        members_count: Number of members
        stripe_invoice_id: Stripe invoice ID
        stripe_invoice_number: Stripe invoice number
        stripe_hosted_url: Stripe hosted invoice URL
        stripe_pdf_url: Stripe invoice PDF URL
        tenant_name: Organization name
        line_items: List of line items to create

    Returns:
        Dict with invoice data including invoice_number

    Raises:
        Exception: On any database error (triggers rollback)
    """
    cursor = conn.cursor()

    try:
        # Insert invoice (invoice_number is generated by calling generate_invoice_number())
        cursor.execute("""
            INSERT INTO invoices (
                invoice_number,
                tenant_id,
                period_start,
                period_end,
                credits_allocated,
                admin_seat_charges,
                total_amount_credits,
                admin_seats_count,
                members_count,
                status,
                issued_at,
                due_date,
                stripe_invoice_id,
                metadata
            ) VALUES (
                generate_invoice_number(),
                %s, %s, %s, %s, %s, %s, %s, %s,
                'pending',
                NOW(),
                NOW() + INTERVAL '7 days',
                %s,
                %s::jsonb
            )
            RETURNING id, invoice_number, issued_at, due_date
        """, (
            tenant_id,
            period_start,
            period_end,
            credits_allocated,
            admin_seat_charges,
            total_amount_credits,
            admin_seats_count,
            members_count,
            stripe_invoice_id,
            psycopg2.extras.Json({
                'tenant_name': tenant_name,
                'generated_by': 'billing_service_transaction',
                'period_label': period_start.strftime('%B %Y'),
                'stripe_invoice_number': stripe_invoice_number,
                'stripe_hosted_url': stripe_hosted_url,
                'stripe_pdf_url': stripe_pdf_url
            })
        ))

        invoice_row = cursor.fetchone()
        invoice_id, invoice_number, issued_at, due_date = invoice_row

        logger.info(f"Created invoice {invoice_number} in transaction")

        # Insert line items
        for item in line_items:
            cursor.execute("""
                INSERT INTO invoice_line_items (
                    invoice_id,
                    item_type,
                    description,
                    quantity,
                    unit_price_credits,
                    total_credits,
                    metadata
                ) VALUES (%s, %s, %s, %s, %s, %s, %s::jsonb)
            """, (
                invoice_id,
                item['item_type'],
                item['description'],
                item['quantity'],
                item['unit_price_credits'],
                item['total_price_credits'],
                psycopg2.extras.Json(item.get('metadata', {}))
            ))

        logger.info(f"Created {len(line_items)} line items in transaction")

        return {
            'id': invoice_id,
            'invoice_number': invoice_number,
            'tenant_id': tenant_id,
            'stripe_invoice_id': stripe_invoice_id,
            'stripe_invoice_number': stripe_invoice_number,
            'stripe_hosted_url': stripe_hosted_url,
            'stripe_pdf_url': stripe_pdf_url,
            'total_amount_credits': total_amount_credits,
            'issued_at': issued_at.isoformat(),
            'due_date': due_date.isoformat(),
            'status': 'pending'
        }

    finally:
        cursor.close()


def consume_credits_fifo_atomic(
    conn: PgConnection,
    tenant_id: str,
    amount: int,
    reason: str
) -> str:
    """
    Atomically consume credits using FIFO strategy.
    Uses raw SQL within a transaction.

    Args:
        conn: PostgreSQL connection (must be in transaction)
        tenant_id: Organization ID
        amount: Credits to consume
        reason: Reason for consumption

    Returns:
        consumption_id

    Raises:
        Exception: If insufficient credits or database error
    """
    cursor = conn.cursor()

    try:
        # Create consumption record
        cursor.execute("""
            INSERT INTO tenant_credit_consumptions (
                tenant_id,
                credit_amount,
                reason,
                consumed_at,
                metadata
            ) VALUES (%s, %s, %s, NOW(), %s::jsonb)
            RETURNING id
        """, (
            tenant_id,
            amount,
            reason,
            psycopg2.extras.Json({
                'source': 'billing_service_transaction',
                'billing_type': 'admin_seat_monthly'
            })
        ))

        consumption_id = cursor.fetchone()[0]

        # Get credit lots ordered by creation date (FIFO)
        cursor.execute("""
            SELECT id, credit_amount
            FROM credit_lots
            WHERE tenant_id = %s
              AND is_active = true
              AND (expires_at IS NULL OR expires_at > NOW())
            ORDER BY created_at ASC
            FOR UPDATE  -- Lock rows for update
        """, (tenant_id,))

        credit_lots = cursor.fetchall()

        # Deduct from lots using FIFO
        remaining = amount

        for lot_id, lot_amount in credit_lots:
            if remaining <= 0:
                break

            if lot_amount <= remaining:
                # Fully consume this lot
                cursor.execute("""
                    UPDATE credit_lots
                    SET credit_amount = 0,
                        is_active = false,
                        updated_at = NOW()
                    WHERE id = %s
                """, (lot_id,))

                remaining -= lot_amount
            else:
                # Partially consume this lot
                new_amount = lot_amount - remaining
                cursor.execute("""
                    UPDATE credit_lots
                    SET credit_amount = %s,
                        updated_at = NOW()
                    WHERE id = %s
                """, (new_amount, lot_id))

                remaining = 0

        # Verify we consumed the full amount
        if remaining > 0:
            raise Exception(f'Insufficient credits: needed {amount}, short by {remaining}')

        logger.info(f"Consumed {amount} credits atomically for tenant {tenant_id}")

        return str(consumption_id)

    finally:
        cursor.close()
